### ISSUE TITLE
Request to move ts-for-gir to Gjsify organization

### ISSUE THREAD

**Issue by JumpLink** [gjsify/ts-for-gir#102]
Hello @sammydre,

I hope this message finds you well. I have been working on a number of TypeScript tools for Gjs under the [Gjsify](https://github.com/orgs/gjsify) organization, and I was wondering if you would be open to moving the project "ts-for-gir" to this organization as well.

I understand that you have been the owner to this project so far, and I would be more than happy for you to retain full access if you want. However, having the project under the Gjsify organization would allow me to add more contributors, update the project's description, and make other changes that would help to promote the project and attract more users.

I understand that this request may not align with your plans for the project, and if that is the case, I understand and respect your decision. If you are open to this proposal, please let me know and we can discuss next steps.

Thank you for your time and consideration.

Best regards,
JumpLink

**Comment by sammydre** [comment]
Hi @JumpLink ,

For some time now you've been putting a lot more into this project than me.

I'm happy for it to move to the Gjsify organization.

Let me know how to proceed.

Cheers,
Sam

**Comment by JumpLink** [comment]
Hi @sammydre,
thank you!

It should be enough if you enter "gjsify" as the new owner in the settings of this project: Settings -> Danger Zone -> Transfer ownership -> Specify an organization or username -> "gjsify". If you do not automatically stay in the project, I would add you back then.

Cheers,
Pascal :)

**Comment by sammydre** [comment]
Hmm, that gives me: "You don’t have the permission to create public repositories on gjsify"

Looks like I'll need permission to create the destination repo?

**Comment by JumpLink** [comment]
@sammydre I have added you to the organisation now, it should work now

**Comment by sammydre** [comment]
Looks like that’s worked 😀

**Comment by JumpLink** [comment]
Thank you very much :)
