### ISSUE TITLE
`gchar*` C-types should be mapped to `string | null` in TypeScript

### ISSUE THREAD

**Issue by ncpa0cpl** [gjsify/ts-for-gir#108]
Many Gtk Widgets properties have a C type `gchar*`, ts-for-gir is assigning those properties `string` type in the TypeScript declarations. However  `gchar*` is a pointer and can be assigned a null. This is something I've been doing before, for example with `Gtk.Button.label` and now that I've started using types generated from ts-for-gir I am getting those errors:
> error TS2322: Type 'string | null' is not assignable to type 'string'.

**Comment by JumpLink** [comment]
@ncpa0cpl Thank you for reporting!
Do you know if this is also the case for `const gchar*`

**Comment by JumpLink** [comment]
@ncpa0cpl In the `Gtk-4.0.gir` file for `Gtk.Button.label` there is this defined:

```xml
      <property name="label"
                writable="1"
                transfer-ownership="none"
                setter="set_label"
                getter="get_label"
                default-value="NULL">
        <attribute name="org.gtk.Property.get" value="gtk_button_get_label"/>
        <attribute name="org.gtk.Property.set" value="gtk_button_set_label"/>
        <doc xml:space="preserve"
             filename="gtk/gtkbutton.c"
             line="214">Text of the label inside the button, if the button contains a label widget.</doc>
        <type name="utf8" c:type="gchar*"/>
      </property>
```

Normally, if this parameter is `nullable`, this would be defined in the Gir file with ` nullable="1"` like this:

```xml
        <parameter name="user_data"
                   transfer-ownership="none"
                   nullable="1"
                   allow-none="1"
                   closure="1">
          <doc xml:space="preserve"
               filename="gtk/gtkmenubutton.h"
               line="42">User data passed to gtk_menu_button_set_create_popup_func()</doc>
          <type name="gpointer" c:type="gpointer"/>
        </parameter>
```

But for the case of `label` there is also `default-value="NULL"` defined, but not `nullable="1"`. So the question is, should ts-for-gir handle properties with `default-value="NULL"` as `nullable`? I think this would make sense.

The the [GObject Introspection documentation](https://gi.readthedocs.io/en/latest/annotations/giannotations.html#default-basic-types) also says, that `utf8` is a `string encoded in UTF-8, not containing any embedded nuls`.

**Comment by ncpa0cpl** [comment]
> @ncpa0cpl Thank you for reporting! Do you know if this is also the case for `const gchar*`?

Yes, I just tested it to make 100% sure, `const gchar*` is just a regular pointer to a constant value, the value cannot be mutated but the pointer can change. (A constant pointer would be declared something like `char *const`.)

I ran this code:
```c
#include <stdio.h>

int main()
{
    const char *ptr;

    printf("Is NULL: %d\n", ptr == NULL);

    char *str1 = "Hello";
    ptr = str1;

    printf("Is NULL: %d\n", ptr == NULL);

    ptr = NULL;

    printf("Is NULL: %d\n", ptr == NULL);

    return 0;
}
```
And this was the output:

> Is NULL: 1
> Is NULL: 0
> Is NULL: 1

As for

> The the [GObject Introspection documentation](https://gi.readthedocs.io/en/latest/annotations/giannotations.html#default-basic-types) also says, that utf8 is a string encoded in UTF-8, not containing any embedded nuls.

I think this just means that the character string behind the pointer cannot include NULL characters, which is not the same thing as null pointer.

**Comment by JumpLink** [comment]
@ncpa0cpl With my latest commit we allow `null` for properties which are by default `null`. Possibly this is already enough, could you test this?

**Comment by JumpLink** [comment]
Thanks for looking into this, I wrote my last comment when I hadn't seen this yet.

Example urf8 types:
* `<type name="utf8" c:type="const char*"/>`
* `<type name="utf8" c:type="gchar*"/>`
* `<type name="utf8" c:type="char**"/>`
* `<type name="utf8"/>`

Did you think all of them are nullable except the last one? If you are sure I can implement this, too

**Comment by JumpLink** [comment]
@ncpa0cpl Okay I have implement it this way in my last commit, please let me know if you found a case where Gjs handles this in some other way (for example if Gjs converts this to an empty string instead of null or something like this).

**Comment by JumpLink** [comment]
@ncpa0cpl We are currently handle **all** pointers as nullable now. Not only `gchar*`. I'm not quite sure if this is a good thing, possibly we can just assume that the pointers are always set and this would otherwise be a bug in the library, what do you think?

**Comment by ncpa0cpl** [comment]
> possibly we can just assume that the pointers are always set and this would otherwise be a bug in the library.

So this would vary between different interfaces and libraries. In some cases a pointer would never be null out of the box, and out of those cases there would be some where if you'd assign it a NULL it would cause a Segmentation Fault. But on the other hand there would be cases where the given library expects a pointer could be NULL and handle it properly. I don't think it's possible to determine if it's safe for a given pointer to be null or not just from the introspection.

Personally I only worked with Gtk and the libraries related to it (Gdk, GLib etc.) and have not encountered a situation where a class or interface had to be assigned NULL (like the Button label). But this is just my very limited experience with a few of all the libraries that use gir.

There's also an argument to be made that from the point of view of a type system like TypeScript, it is irrelevant whether it's safe to assign some value to a variable, and all that matters is whether the types match. For example, in Javascript you can initialize an array using `Array.from({ length: number })`, the length parameter accepts a number, and there are no unsigned numeric types in TypeScript so if you give it a negative number TS won't complain at all. `length` must be a number and any negative number is still a number so from a point of view of a type system `Array.from({length: -1})` is perfectly valid, even though it's clearly a mistake to do so.

By the same logic, even if setting a pointer a NULL is a mistake/bug, from the perspective of a type system it's valid to do so.

I am not that familiar with all the different gir libraries but, if in most cases interface/class pointers are not supposed to be NULL, then you could make the TS typings for them non-nullable, and then just tell the users that in the rare cases where it's ok to set those pointers to NULL, but the typings suggest otherwise, they should ignore the errors, and use the `@ts-ignore` or `@ts-expect-error` clauses.

Perhaps the ideal solution would be to make this a configuration option. So that you can chose whether all pointers are going to be nullable or just some of them.

These are all my thoughts on this matter, I don't really have a very strong opinion on what is the best approach here, though I am leaning towards "all pointers are nullbable".

**Comment by JumpLink** [comment]
@ncpa0cpl  Thank you for your detailed explanation. After going over the `*.gir` files again, I noticed that many pointers are marked as nullable but not all. In some cases the documentation says that an object is always returned, for example in `Gio.file_new_for_path(path: string)`, even if `path` is not valid. Accordingly, never null is returned either.

In this case `path`  has this type: `<type name="filename" c:type="const char*"/>`, so it is a nullable pointer to a string, but if I pass `null`, I get a runtime error. From a type system point of view, you are of course right that this does not catch any logical errors. On the other hand, TypeScript's type system is a special case, as it can also define a lot of what the developer in his API wants to allow and what to disallow. Does the developer want to allow `null` here? Then it will be specified, otherwise it won't and since GObject Introspection allows an explicit specification for this, we should also refer to it.

By the way, the type system of TypeScript can theoretically even [disallow negative values](https://stackoverflow.com/a/69413070/1465919) (not at runtime, of course).

I think it would be an error if a object or pointer can be `null`, but this was not specified in the `*.gir.` file. So I think we don't need to mark every pointer as nullable, only if this is defined in the `*.gir`. If something can be null, but this was not specified, then this is an error in the *`.gir` file and should be fixed in the `*.gir` file.

So I'm going to revert my changes and limit this to utf8 string pointers for now. Should one of us or anyone else have new insights, this discussion can be continued.

**Comment by JumpLink** [comment]
Good question, maybe the value is initial `null`, but should not be set to `null` and this information is auto generated.

**Comment by JumpLink** [comment]
The new version with nullable UTF-8 string is out, if there is any new feedback we can further adjust the code accordingly
