### ISSUE TITLE
Provide `system` and `gettext` as ESM

### ISSUE THREAD

**Issue by nahuelwexd** [gjsify/ts-for-gir#114]
Both `system` and `gettext` are currently available to be imported as ECMAScript Modules, I think since GJS supports ESM. It would be nice to be able to import them in such a way using ts-for-gir, since the default GNOME Builder template imports `system` that way :)

**Comment by JumpLink** [comment]
I agree, we should support the following:

```ts
import gettext from 'gettext';
import system from 'system';
```

And something like that:
```ts
import { exit } from 'system';
import { ngettext as _ } from 'gettext';
```

**Comment by CharlieQLe** [comment]
Cairo is another one like this, it doesn't use the `gi://` format as far as I know. However, Cairo does not provide named exports according to the [docs](https://gjs-docs.gnome.org/gjs/esmodules.md).

**Comment by JumpLink** [comment]
Added in #106
