### ISSUE TITLE
@girs/node-gtk node-gtk.cjs contains code in esm format despite the extension

### ISSUE THREAD

**Issue by Exidex** [gjsify/ts-for-gir#119]
node-gtk.cjs file in [@girs/node-gtk](https://www.npmjs.com/package/@girs/node-gtk?activeTab=code) has esm format. File contains following:
```
    import * as gi from 'node-gtk';
    export { gi };
    export default gi;
```
node-gtk.js is identical

**Comment by Exidex** [comment]
looking at [@girs/node-gtk](https://www.npmjs.com/package/@girs/node-gtk?activeTab=code) more, it looks like it uses snake case naming, which seems incorrect. on the other hand [@girs/node-gtk-4.0](https://www.npmjs.com/package/@girs/node-gtk-4.0) has camel case naming but doesn't contain the types for node-gtk itself (e.g. startLoop function)

**Comment by JumpLink** [comment]
> looking at [@girs/node-gtk](https://www.npmjs.com/package/@girs/node-gtk?activeTab=code) more, it looks like it uses snake case naming, which seems incorrect. on the other hand [@girs/node-gtk-4.0](https://www.npmjs.com/package/@girs/node-gtk-4.0) has camel case naming but doesn't contain the types for node-gtk itself (e.g. startLoop function)

Yes this is on my TODO, see Include only desired types` #106

**Comment by JumpLink** [comment]
@Exidex The esm format should be fixed and published on NPM, now

**Comment by JumpLink** [comment]
@Exidex There were other problems that should be fixed now, I would be happy if you test this again.
