### ISSUE TITLE
On node-gtk, GObject.Object lacks definition of disconnect()

### ISSUE THREAD

**Issue by peat-psuwit** [gjsify/ts-for-gir#126]
Node-gtk implements `object.disconnect()` as a native override [here](https://github.com/romgrk/node-gtk/blob/79b6ef4469b6eea770e273574193d40a54bce5a5/src/gobject.cc#L379-L397). The method was there with an earlier version of ts-for-gir [1], so this is technically a regression.

[1] If my reflog doesn't fail me, in commit f5c8a249f from Feb 2022.

**Comment by JumpLink** [comment]
@peat-psuwit Thank you for the report. I'm focusing more on GJS myself right now instead of node-gtk, so I'm depending on feedback like yours here. I have added the `disconnect` method again and will make a new release soon. Can you check that again then?

**Comment by peat-psuwit** [comment]
Thank you for a quick response! I checked the latest commit on gjsify/types, and it seems to work. The signature looks correct.

I would imagine that it could be added to the `GObject.Object`'s declaration, but as it is seems to work as well.

That said, I also have some other comments on the type that I didn't file issues yesterday (mostly because it was long past bedtime 😅). Will file them separately.

**Comment by JumpLink** [comment]
@peat-psuwit yes that's right, we could optimize that
