### ISSUE TITLE
node-gtk uses snake_case for property names at constructor, not camelCase

### ISSUE THREAD

**Issue by nahpotato** [gjsify/ts-for-gir#131]
This is not properly documented in node-gtk, but it is basically the title.

**Comment by cmumme** [comment]
Are you saying that the typings for node-gtk should be changed such as:
```ts
let app = new gtk.Application({ applicationId: "org.me.app" })
```
becomes:
```ts
let app = new gtk.Application({ application_id: "org.me.app" })
```

If so, you'd be correct, I was attempting to use the above (camelCase) syntax in my code, as that's what the generated types use. However this obviously doesn't work, forcing me to use either ``//@ts-ignore`` or resorting to a different overload of the ``ApplicationWindow`` constructor that doesn't use the incorrectly typed ``ConstructorProperties``.

I'll look into this and see if it's something I can fix myself, but I haven't touched the ts-for-gir codebase yet so I'm not sure if it's a simple fix or not.
