### ISSUE TITLE
Request for types of gnome bluetooth 3.0

### ISSUE THREAD

**Issue by jerrywcy** [gjsify/ts-for-gir#137]
Hello! I am recently writing a type definition for an application written in gjs. I really appreciate your work and they helped me really a lot. 

However, one part is missing: the application uses version 3.0 of Gnome Bluetooth, and I only found @girs/gnomebluetooth-1.0. Am I missing something? If so, please tell me where I can find types for gnome Bluetooth 3.0? If not, could you please provide types for gnome Bluetooth 3.0?

**Comment by JumpLink** [comment]
Hi @jerrywcy, thanks for this question. On Fedora you can install the `gnome-bluetooth-libs-devel` package which contains the *.gir file you are looking for: `/usr/share/gir-1.0/GnomeBluetooth-3.0.gir`.

On Arch Linux I found it here: https://archlinux.org/packages/extra/x86_64/gnome-bluetooth-3.0/files/

By default, `ts-for-gir` looks for the *.gir files in `/usr/share/gir-1.0/`, so it should be enough to install the package. If you are using Ubuntu, please let me know what the package is called there and I will add it to the documentation.

If you also need very specific types, you can also create a PR with the corresponding *.gir files. Just put the *.gir file in `./girs`, as soon as this is merged I will generate and publish the NPM types for it in the next cycle

I have now installed the package on my system and will publish the NPM types for it in the next release.

**Comment by JumpLink** [comment]
@jerrywcy It's now published on NPM: https://www.npmjs.com/package/@girs/gnomebluetooth-3.0

Feel free to reopen this issue if something is wrong with the package.
