### ISSUE TITLE
Proposal to Omit Version Strings in NPM Package Type Generation for Ambient Modules

### ISSUE THREAD

**Issue by JumpLink** [gjsify/ts-for-gir#139]
We are considering the possibility of omitting version strings for ambient modules in our NPM packages. This proposal arises from the understanding that the conflicts typically addressed by version strings can be mitigated by ensuring that conflicting NPM packages are not installed simultaneously.

It is also conceivable that ts-for-gir should only support the generation of NPM packages in the future, which would simplify many things and would not change the fact that the types can still be generated locally for your own project, only then as local NPM packages, e.g. for a monorepo.

See this discussion for more information: https://github.com/gjsify/types/issues/1#issuecomment-1813856410

**Comment by bennypowers** [comment]
Thank you for opening this issue. In the future, import maps will provide a comprehensive solution here, but in the mean time, it would be very helpful to extension and app developers to get these types without query strings

**Comment by JumpLink** [comment]
I'll see if it's enough to make a special treatment for NPM packages, if that leads to other problems we can undo it again. [This simple commit](https://github.com/gjsify/ts-for-gir/commit/1e1580cb0568b934473f7e4981a9f558c206691e) contains this changes. I'm leaving the issue open as I want to wait for feedback.
