### ISSUE TITLE
Configure additional async functions

### ISSUE THREAD

**Issue by swsnr** [gjsify/ts-for-gir#140]
Hello,

I'm using the new async `FileDialog` in Gtk.  Unfortunately, the heuristic ts-for-gir employs to detect async functions doesn't catch `Gtk.FileDialog.open` and `Gtk.FileDialog.select_folder` (I guess it's because they're missing the `_async` suffix?).   To work around this issue I have to cast to convince Typescript that I do indeed get a promise back, e.g.

```typescript
 const file = await (Gtk.FileDialog.new().select_folder(
        this.root as Gtk.Window,
        null,
) as unknown as Promise<Gio.File>)
```

That's not nice, but I understand that the introspection metadata ts-for-gir relies on currently doesn't expose any markers for async functions, so it's hard or even impossible to detect all async functions.

As an alternative, I'd be cool if we could specify additional promisified functions explicitly in configuration, e.g. mapping type names to a list of promisified function names mapped to the corresponding start and finish functions.

```json
{
  "promisifyFunctions": {
    "Gio.FileDialog": [
      "select_open": ["select_folder", "select_folder_finish"]
    ]
  }
}
```

Would that be a desirable change?  If so I could look into making a pull request.  As far as I can see it shouldn't be too hard; `GirModule.overloadPromisifiedFunctions` would just need to make an extra lookup into this new config map and generate the extra overload.

**Comment by JumpLink** [comment]
Hi @swsnr, yes, we could do it that way 👍

**Comment by swsnr** [comment]
Cool, I'll look into making a pull request, but might take a while.

**Comment by swsnr** [comment]
I'm closing this, because realistically I don't have time to make this change any time soon, and I'm not sure if it's worth it, given that gobject introspection supposedly supports async annotations now.
