### ISSUE TITLE
The `buildType` option doesn't work yet.

### ISSUE THREAD

**Issue by vixalien** [gjsify/ts-for-gir#168]
In the CLI, there's supposed to be an option called `buildType` to change the output format to just generate a .d.ts file, however that doesn't seem to be implemented yet.

Because of this, ts-for-gir can't really replace gi.ts right now

**Comment by JumpLink** [comment]
@vixalien Unfortunately, we have not yet updated the documentation on the main branch, but hopefully this will happen soon. The option is still available in the 3.x branch. On the main branch the option has been removed, why do you need this to replace gi.ts?

**Comment by vixalien** [comment]
We use gi.ts to generate typescript declaration files like the ones at https://gitlab.gnome.org/BrainBlasted/gi-typescript-definitions.

These files are included as submodules in apps where we can't use npm to install the types like Decibels and GNOME Sound Recorder.

I thought gi.js was being replaced by this so I thought this feature would be too much to miss.

**Comment by JumpLink** [comment]
@vixalien I have removed the option because it is should not absolutely necessary and this simplifies the maintenance effort. You can still generate the types, with the difference that a separate folder is created for each generated type and a *.js and package.json are generated in addition to the *.d.ts (and other files like ambient imports etc).


However, the package.json is practical because it makes it easier to import the types, as typescript can then resolve this more easily. The `tsconfig.json` contains the path to the folder, e.g. like this:


```json
{
  "compilerOptions": {   
    "baseUrl": "../gi-typescript-definitions",
    "types’": ["gjs", "gio-2.0"],
    "module": "ESNext",
    "moduleResolution": "bundler"
  }
}

```

Alternatively you can use a package manager like `npm`, `pnpm` or `yarn` and add the folder `gi-typescript-definitions` to the workspace, this way the self-generated NPM packages should also be recognised.

Then TypeScript should know the types for the imports like this:
```
import GLib from ‘gi://GLib?version=2.0’;
```
So no bundler is necessary to use the types in this way. However, a bundler can also be used if, for example, one is used anyway, in which case the types could also be imported in this way:

```ts
import GLib from ‘@girs/glib-2.0’;
```

The .js behind this package is then imported by the module itself via ` import GLib from ‘gi://GLib?version=2.0’;` which should then be resolved by the bundler. So there should be several ways to use the self-generated types anyway. Or do you have such a special setup that this is not possible for you? Then please explain this to me in more detail, we are of course very interested in everyone being able to use the types.

**Comment by vixalien** [comment]
GJS doesn't use `package.json`, so it is unused in our use-case

> For this you need to add the path of your generated types (e.g. gi-typescript-definitions) and the types to the tsconfig.json like this:

This already worked with gi-typescript-definitions with the generated [`gi.d.ts`](https://gitlab.gnome.org/BrainBlasted/gi-typescript-definitions/-/blob/nightly/gi.d.ts?ref_type=heads) file. This file serves as an index for all the packages. The gi.d.ts file was 9generated by applying this pending MR](https://gitlab.gnome.org/ewlsh/gi.ts/-/merge_requests/1)

> The .js behind this package is then importing the real GJS module via import GLib from 'gi://GLib?version=2.0'; which should then be resolved by your bundler. This has the advantage that you do not have to add and maintain the types to tsconfig.json in this way.

When using GJS directly, there is no need for any `.js` file because GJS will resolve the GI imports directly.

All in all, the package.json and .js files tell me this is made for compatibility with node.js (presumably node-gtk). It also says in the README that support has been dropped for node-gtk, but we still have those files.

I strongly suspect that not generating these files (or at least adding an option not to) will ease the development process.

I have an example of an app where I use `gi-typescript-definitions` with a bundler (in this case, esbuild), and I told esbuild just not to resolve the `gi://*` files like this:

```js
  external: ["gi://*", "format", "gettext"],
```

https://github.com/vixalien/muzika/blob/6c19937b127e7e968bccb03ca345e08bddf12085/lib/build.js#L25C1-L25C45

If you are using another bundler and the `@girs/glib-2.0` import syntax, you can write a simple plugin for your bundler that would rewrite that import to `gi://GLib-2.0`.

I would also like to know if any apps import the types using the  `@girs/glib-2.0`  from node

**Comment by JumpLink** [comment]
@vixalien Thanks for the feedback, I have a few more questions about your use case: Do you write your sources in TypeScript? And if so, how do you transpile the sources to JavaScript? Do you use ` tsc `  for this? If so, how did you make it available on your system? I know that GJS does not support package.json. In the two suggestions I tried to explain, the package.json is not used at runtime but only in the previous process.

**Comment by JumpLink** [comment]
I have now created a working example that shows how to generate the types themselves to create a simple GJS application with `tsc`: https://github.com/gjsify/ts-for-gir-local-tsc-example

**Comment by JumpLink** [comment]
And here an almost identical example, but uses `esbuild` instead of `tsc` to build the TypeScript code: https://github.com/gjsify/ts-for-gir-local-esbuild-example

**Comment by JumpLink** [comment]
You can find more examples in the ts-for-gir repository, including some that use Vite and Webpack as bundlers. The examples in the ts-for-gir repository all use yarn instead of npm, but just like the examples I have created for you, they use the workspace feature to make the locally created types known to the development environment. All these examples use GJS in the last step.

**Comment by JumpLink** [comment]
@vixalien Did my instructions help you or do you think it would be better to read support without package.json?

**Comment by vixalien** [comment]
Hello. I didn't take much time to examine the situation so forgive me if my responses are a bit shallow, but it seems the issue is that the new direction of the project is trying to work with other JS runtimes (Node, Bun, Deno, etc...) while kind of forgetting GJS. I say this because of the addition of `package.json` and moving to support registries `npm`/`jsr` which are not compatible with GJS.

With the current approach, ts-for-gir doesn't work with GJS, so we are still using outdated gi.ts. It would be nice to atleast have the old behavior of gi.ts and then maybe improve it from down the road.

> As far as I know, the GNOME Bundler is also working on TypeScript support.

It's Workbench that's working on TypeScript support, and that actually requires projects like gi.ts and ts-for-gi, not the other way around.

> By the way: For the future I plan to support [JSR](https://jsr.io/) which is a TypeScript runtime independent package registry

Just so you know, this brings absolutely nothing to the table for GJS. GJS doesn't support package registries at all. Unless some work is done, jsr/node/cloudinary will almost mean nothing to GJS (unless you use BOTH Node and GJS, but that's another topic).

> What I could also add would be support for a declaration file that contains all generated types, so that only one entry in tsconfig.json is necessary, if that would still help.

Yes. The package.json and all the additional files are really unused for GJS-based typescript solutions. All that's needed is that declaration file that links all generated types, like `gi.d.ts`. GJS can't do `import Gtk from "@girs/gtk-4.0"`.

**Comment by JumpLink** [comment]
@vixalien Okay then I will try to implement it again to be independent of a `package.json` and a bundler. But I can't say just yet how quickly this will happen

**Comment by vixalien** [comment]
Seems like recent changes made this possible (kinda). I have one question:

In the generated files, say `gtk-4.0.d.ts`, there seem to be an import of `./gtk-4.0-import.d.ts` which in turn imports `./gtk-4.0.js` leading to a circular import. Is this behaviour correct?

**Comment by JumpLink** [comment]
This was not a conscious decision, but does not cause any problems as far as I know, if you think it can be cleaner I am happy about suggestions :)

**Comment by vixalien** [comment]
Seems like I was still using v3 locally. The types generated are in the following format:

![image](https://github.com/gjsify/ts-for-gir/assets/37999241/56d92cf3-a16d-434f-b473-f27b5fd0c6f0)

With v4, each file generate a single folder, even with `buildType` set to `lib`.

![image](https://github.com/gjsify/ts-for-gir/assets/37999241/2364d1ad-9451-4186-ae7a-87ee164b81cd)

As you can probably acknowledge, all of these files are useless for us except the `gtk-4.0.d.ts` and maybe `gtk-4.0-ambient.d.ts`

**Comment by vixalien** [comment]
Yes :)

I'm having issues understanding the `buildType` option :( at first I thought it might be closest to what GJS does.

I hope when the `all.d.ts` file is generated (probably when `buildType` is set to `types`) the other files (`README`, `tsconfig.json`, `typedoc.json`, ... won't be generated as well.

**Comment by JumpLink** [comment]
@vixalien Is now implemented with the latest version and is the default. `package.json` support must now be explicitly activated with `--package`. Please try it out :)

**Comment by vixalien** [comment]
Hey! Thanks very much for working on this!! I'll be trying it out soon 👀
