### ISSUE TITLE
Can't construct Graphene.Point

### ISSUE THREAD

**Issue by flexagoon** [gjsify/ts-for-gir#170]
When trying to do the following:

```typescript
new Graphene.Point({x: 0.5, y: 0.5})
```

Typescript throws an error: `Expected 0 arguments, but got 1.`

However, constructing a point like that works, and is widely used in js extensions:

https://sourcegraph.com/search?q=context:global+graphene.point%28&patternType=keyword&sm=0

**Comment by flexagoon** [comment]
Same thing happens when trying to construct `Gdk.RGBA` by passing color values into the constructor.

**Comment by JumpLink** [comment]
@flexagoon I have tested this with `@girs/graphene-1.0` v`1.0.0-4.0.0-beta.5` and here are the types correct. I think it's time to make this version stable

**Comment by flexagoon** [comment]
Can confirm this works fine in the latest version
