### ISSUE TITLE
Missing promisified overloads

### ISSUE THREAD

**Issue by JumpLink** [gjsify/ts-for-gir#171]
@ewlsh Some promisified methods are missing, for example for `Gio.read_async` + `Gio.read_finish` or `Gio.File.load_contents_async` + `Gio.File.load_contents_finish`

**Comment by ewlsh** [comment]
I'm looking at what happened here, should have a fix in the next few weeks.

**Comment by swsnr** [comment]
I'm upgrading a GNOME extension to ts-for-gir 4.0.0 types, and noticed missing promisified overloads as well:

- `Soup.Session.send_async`
- `Soup.Session.send_and_read_async`
- `Gio.File.delete_async`

Is this the same issue, or should I rather open a new one?

**Comment by JumpLink** [comment]
@swsnr I think this will be the same problem, so it will be correct here.

@ewlsh In v3 I just checked if there is a method that ends with `_async` and one that ends with `_finish`, but that might not be so clean either, especially since there are some cases where this convention is not followed

**Comment by JumpLink** [comment]
@ewlsh could you explain a bit how this works with you new parser atm? Maybe a good start to get into your code base.

**Comment by ewlsh** [comment]
Sorry for the delay here, adding some context and potential fixes here: https://github.com/gjsify/ts-for-gir/pull/177

**Comment by swsnr** [comment]
@ewlsh @JumpLink Is there any way forward here, or at least some reasonable workaround?  At least for my use cases that's quite a serious regression :grimacing: and I'm still stuck with the types generated with the old 3.x version.

**Comment by Totto16** [comment]
> @ewlsh @JumpLink Is there any way forward here, or at least some reasonable workaround? At least for my use cases that's quite a serious regression 😬 and I'm still stuck with the types generated with the old 3.x version.

A "reasonable" workaround is, the casting of these functions, it is ugly, but doable 🤷🏼‍♂️ see an example here
https://github.com/oae/gnome-shell-pano/blob/overhaul-code-highlighting/src/utils/linkParser.ts#L32-L37

and here my personal type helper for this: 
https://github.com/oae/gnome-shell-pano/blob/overhaul-code-highlighting/src/types/gio.d.ts#L26-L32

**Comment by JumpLink** [comment]
@swsnr This is definitely an issue that I would like to fix as soon as I find the time. Apart from that, the 4.x types seem to work fine

**Comment by JumpLink** [comment]
@swsnr, @Totto16 I have now completed @ewlsh PR #177, so it should work now. I'd love to get some feedback on it, as I haven't tested it extensively yet, but so far it looks good.

**Comment by swsnr** [comment]
@JumpLink I'd love to test this. Will you push new Npm releases with updated types?

**Comment by JumpLink** [comment]
Yes, I already have. The types for GNOME Shell will follow (probably tonight when the kids are in bed)
