### ISSUE TITLE
Add `gi.d.ts` index file

### ISSUE THREAD

**Issue by vixalien** [gjsify/ts-for-gir#173]
Hi. Thanks for working on this!

I see there's now an option to generate an index `tsconfig.json`. Would it also be possible to generate a `gi.d.ts` file similar to https://gitlab.gnome.org/BrainBlasted/gi-typescript-definitions/-/blob/nightly/gi.d.ts?ref_type=heads where we can import just one file and have all the types available

**Comment by JumpLink** [comment]
@vixalien Good idea. Would this also solve #168 for you? Maybe a part of it?

**Comment by vixalien** [comment]
Most definitely. In fact the project almost meets the requirements.

I can theoretically do this manually by concatenating the `-ambient.d.ts` into a `gi.d.ts` file and then deleting them as they won't be needed 😅 but an option would be highly appreciated.

I would also delete the `-import.d.ts` files as they would be unused.

**Comment by JumpLink** [comment]
@vixalien Is also now implemented with the latest version and is the default if `package.json` support is disabled. In addition to the `gi.d.ts` with all GIR types, an `index.d.ts` is now also generated. This means that in addition to all GIR types, all types including the GJS core types can be imported by a single file, now.

**Comment by vixalien** [comment]
Wow, you're on a roll! I'll take a look ASAP
