### ISSUE TITLE
`Gtk.ListBox`  should be iterable

### ISSUE THREAD

**Issue by vixalien** [gjsify/ts-for-gir#193]
In GJS, it seems to be iterable. Might also be useful to know which other types are iterable.

See https://github.com/workbenchdev/demos/blob/3d05940216e007b4b3681d8a8d620d5aedcf73fb/src/Drag%20and%20Drop/main.js#L12

**Comment by vixalien** [comment]
I asked which types are known to be iterable in the GNOME JavaScript channel on Matrix, and I got a response from ptomato:

> the iterable types are ones that explicitly have a [Symbol.iterator] method added in modules/core/overrides/*.js. we try to use that sparingly because depending on the type, it can be deceptively more expensive than it looks.

From a quick look, I found the following iterable types:

- `Gio.ListStore`
- `Gio.FileEnumerator` (also has an `[Symbol.asyncIterator]`)
- `Gtk.Widget`

**Comment by hdonnay** [comment]
Relatedly, `Gio.InputStream` has `createSyncIterator` and `createAsyncIterator`: [documentation](https://gjs-docs.gnome.org/gjs/overrides.md#gio-inputstream-createasynciterator)

**Comment by JumpLink** [comment]
Hello @vixalien thanks for the issues, I am currently developing my own GNOME application in TypeScript in my limited free time to do the complete process to the finished application myself. As soon as I have a little more time or have finished the first release, I will concentrate more on ts-for-gir again
