### ISSUE TITLE
adw-1 example on main doesnt exit if window is closed

### ISSUE THREAD

**Issue by MTRNord** [gjsify/ts-for-gir#203]
Taking the example from https://github.com/gjsify/ts-for-gir/tree/f0f46a3218568ecc961afd7f0aaf8d667e9a513a/examples/adw-1-hello and running it in wayland mode on fedora leads to the application still running when the window is being closed. This doesnt happen with the [vite-gtk-4 example](https://github.com/gjsify/ts-for-gir/tree/f0f46a3218568ecc961afd7f0aaf8d667e9a513a/examples/gtk-4-template-vite)

**Comment by JumpLink** [comment]
@MTRNord thank you! Is fixed now
