### ISSUE TITLE
`Gtk.FlowBox.bind_model` should infer the type of the Model.

### ISSUE THREAD

**Issue by vixalien** [gjsify/ts-for-gir#209]
The fixed type should be

```ts
class FlowBox {
  // ...
  bind_model<A = GObject.Object>(model: Gio.ListModel<A> | null, create_widget_func: FlowBoxCreateWidgetFunc<A>): void;
```

It should also be the same for `Gtk.ListBox`

**Comment by JumpLink** [comment]
Should be fixed with version 4.0.0-beta.19. Feel free to try it out and open the ticket again if you have problems :)
