### ISSUE TITLE
Return types wrong for load_contents_async and similar methods

### ISSUE THREAD

**Issue by swsnr** [gjsify/ts-for-gir#211]
With #171 fixed, ts-for-gir now generates wrong return types for some promisified overloads which have a tuple return type with a boolean, such as `Gio.load_contents_async`.

Specifically, `Gio.File.load_contents_async` has this signature:

```typescript
load_contents_async(cancellable?: Cancellable | null): Promise<[boolean, Uint8Array, string]>;
```

But it actually returns a `Promise<[Uint8Array, string]>`.  You can try this yourself with this Gjs snippet which will dump a two-element array under `gjs -m`:

```javascript
import Gio from "gi://Gio?version=2.0";

Gio._promisify(Gio.File.prototype, "load_contents_async");
const file = Gio.File.new_for_uri(import.meta.url);
let result = await file.load_contents_async(null);
console.dir(result);
```

That's because `Gio._promisify` [explicitly drops the frist element of array return values if it's `true` and the array has more than one element](https://gitlab.gnome.org/GNOME/gjs/-/blob/4ee6290eda247cd284b9bdd3a4b6c9c33d518930/modules/core/overrides/Gio.js#L455).  That's also documented at <https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Overrides.md#gio_promisifyprototype-startfunc-finishfunc>

I presume the rationale is that this return value is redundant, because Gio uses this pattern to indicate success or error:  In C which only has a single return value you pass mutable pointers to get the contents and the error, and the return value of `true` or `false` tells you which pointer to look at afterwards. Gjs however already handles this and throws an exception if the function return `false`, so in a Gjs program you'd never see a `false` return value.

I'm not sure this can be typed soundly, but I think a reasonable approximation would be to just drop the first component of a tuple return value if its type is boolean and the array has more than one element.

**Comment by JumpLink** [comment]
@swsnr Thank you for the detailed bug report, I think I was able to fix the bug quickly. I'm publishing the types right now on NPM. You are welcome to test it again :)

**Comment by swsnr** [comment]
@JumpLink Thanks for the quick fix :pray: Works perfect now :tada:
